### ISSUE TITLE
Use and parse JSON-log when executing restic instead of regex-parsing-foo

### ISSUE THREAD

**Issue by Hermsi1337** [mittwald/brudi#12]
For now, we're checking what `restic` has done by parsing the log-output with a `regex`.   
Since this is somehow.. weird.. we should use the json-log option from `restic` instead and parse the output with `json.unmarshal`.

https://github.com/mittwald/brudi/blob/master/pkg/restic/commands.go#L29

**Comment by Hermsi1337** [comment]
We should also ensure restic-support for the current version `0.11.0`

https://github.com/restic/restic/releases

**Comment by YannikBramkamp** [comment]
Do we want to do anything with the `BackupResult` that gets returned throughout `CreateBackup` and `parseSnapshotOut`? We assign values to it (e.g. https://github.com/mittwald/brudi/blob/master/pkg/restic/commands.go#L76), but everything except the error just gets voided at https://github.com/mittwald/brudi/blob/master/pkg/restic/client.go#L62
